POST   http://localhost:8000/api/register

 {
  "name":"Johnpauluh",
    "email":"bennhhypen@gmail.com",
    "password":"1234j567899"
  }
###

POST  http://localhost:8000/api/loginByToken
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMzMDAzMjY0LCJleHAiOjE3MzMwMDY4NjQsIm5iZiI6MTczMzAwMzI2NCwianRpIjoidzF1VjdyNWxHaXNQQVNRaiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.EdBg-B-u2M_o7VVOFC2e9o4HSG3gfn39RKpspzrX4HU

###
POST   http://localhost:8000/api/login

{
    "email":"bennhhypen@gmail.com",
    "password":"1234j567899"
  }

###
POST   http://localhost:8000/api/brts
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMzMDAzMjY0LCJleHAiOjE3MzMwMDY4NjQsIm5iZiI6MTczMzAwMzI2NCwianRpIjoidzF1VjdyNWxHaXNQQVNRaiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.EdBg-B-u2M_o7VVOFC2e9o4HSG3gfn39RKpspzrX4HU

{
  "brt_code": "BRseddhfdjsxddsjhxkxddd3h4dhjbhh58",
  "reserved_amount": 1080.50,
  "status": "active"
}


###
GET  http://localhost:8000/api/brts 
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMzMDAzMjY0LCJleHAiOjE3MzMwMDY4NjQsIm5iZiI6MTczMzAwMzI2NCwianRpIjoidzF1VjdyNWxHaXNQQVNRaiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.EdBg-B-u2M_o7VVOFC2e9o4HSG3gfn39RKpspzrX4HU

###
GET  http://localhost:8000/api/brts/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMzMDAzMjY0LCJleHAiOjE3MzMwMDY4NjQsIm5iZiI6MTczMzAwMzI2NCwianRpIjoidzF1VjdyNWxHaXNQQVNRaiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.EdBg-B-u2M_o7VVOFC2e9o4HSG3gfn39RKpspzrX4HU



###
PUT  http://localhost:8000/api/brts/7
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMzMDAzMjY0LCJleHAiOjE3MzMwMDY4NjQsIm5iZiI6MTczMzAwMzI2NCwianRpIjoidzF1VjdyNWxHaXNQQVNRaiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.EdBg-B-u2M_o7VVOFC2e9o4HSG3gfn39RKpspzrX4HU

{
  "reserved_amount": 10440.50,
  "status": "active"
}

###
DELETE   http://localhost:8000/api/brts/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMzMDAzMjY0LCJleHAiOjE3MzMwMDY4NjQsIm5iZiI6MTczMzAwMzI2NCwianRpIjoidzF1VjdyNWxHaXNQQVNRaiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.EdBg-B-u2M_o7VVOFC2e9o4HSG3gfn39RKpspzrX4HU

