POST   http://localhost:8000/api/register

 {
  "name":"Johnpauluh",
    "email":"bennhhypen@gmail.com",
    "password":"1234j567899"
  }
###
POST  http://localhost:8000/api/loginByToken
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMyOTc4MTgyLCJleHAiOjE3MzI5ODE3ODIsIm5iZiI6MTczMjk3ODE4MiwianRpIjoidGhjQ3hweTJSOHdGMjZ3TiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.FrZSrOZMchWbkWQCQf34khxNhzbsKciUnPn9IG7hGRs
###
POST   http://localhost:8000/api/login

{
    "email":"bennhhypen@gmail.com",
    "password":"1234j567899"
  }

###
POST   http://localhost:8000/api/brts
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMyOTc4MTgyLCJleHAiOjE3MzI5ODE3ODIsIm5iZiI6MTczMjk3ODE4MiwianRpIjoidGhjQ3hweTJSOHdGMjZ3TiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.FrZSrOZMchWbkWQCQf34khxNhzbsKciUnPn9IG7hGRs

{
  "brt_code": "BRkT12mjk3h4hbhh58",
  "reserved_amount": 100.50,
  "status": "active"
}


###
GET  http://localhost:8000/api/brts 
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMyOTc4MTgyLCJleHAiOjE3MzI5ODE3ODIsIm5iZiI6MTczMjk3ODE4MiwianRpIjoidGhjQ3hweTJSOHdGMjZ3TiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.FrZSrOZMchWbkWQCQf34khxNhzbsKciUnPn9IG7hGRs

###
GET  http://localhost:8000/api/brts/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMyOTc4MTgyLCJleHAiOjE3MzI5ODE3ODIsIm5iZiI6MTczMjk3ODE4MiwianRpIjoidGhjQ3hweTJSOHdGMjZ3TiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.FrZSrOZMchWbkWQCQf34khxNhzbsKciUnPn9IG7hGRs



###
PUT  http://localhost:8000/api/brts/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMyOTc4MTgyLCJleHAiOjE3MzI5ODE3ODIsIm5iZiI6MTczMjk3ODE4MiwianRpIjoidGhjQ3hweTJSOHdGMjZ3TiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.FrZSrOZMchWbkWQCQf34khxNhzbsKciUnPn9IG7hGRs

{
  "reserved_amount": 10440.50,
  "status": "active"
}

###
DELETE   http://localhost:8000/api/brts/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzMyOTc4MTgyLCJleHAiOjE3MzI5ODE3ODIsIm5iZiI6MTczMjk3ODE4MiwianRpIjoidGhjQ3hweTJSOHdGMjZ3TiIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.FrZSrOZMchWbkWQCQf34khxNhzbsKciUnPn9IG7hGRs

